### ISSUE TITLE
Issue in downloading tiles

### ISSUE THREAD

**Issue by GokulGeo** [jochenklar/wms-downloader#2]
I am getting the error like this
 `Traceback (most recent call last):
  File "c:\users\lenovo\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lenovo\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lenovo\anaconda3\Scripts\wms-downloader.exe\__main__.py", line 7, in <module>
  File "c:\users\lenovo\anaconda3\lib\site-packages\wms_downloader\download.py", line 53, in main
    create_vrt_file(config)
  File "c:\users\lenovo\anaconda3\lib\site-packages\wms_downloader\download.py", line 104, in create_vrt_file
    subprocess.check_call(args)
  File "c:\users\lenovo\anaconda3\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\lenovo\anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\lenovo\anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\lenovo\anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

My config.yml is 
**service:
  version: 1.0.0
  url: https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities
  srs: EPSG:4326
  format: jpeg
  layer: s2cloudless-2018
bbox:
  west: 97.0001388889999987
  south: 29.0001388889999987
  east: 94.9998611110000013
  north: 26.9998611110000013

size: 0.70312500000000000000
resolution: 1024
timeout: 300
projection: EPSG:4326
directory: cloudless-images
vrtfile: tiles.vrt
tmpfile: /tmp/wms.xml**

**Comment by luuk777w** [comment]
You need GDAL
https://gdal.org/
